global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'docker'
    static_configs:
    - targets: ['10.0.1.102:8080', '10.0.1.103:8080']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.102:9100', '10.0.1.103:9100']
